### PR TITLE
Add the Cross Entropy cost Function to the Neural network

### PR DESCRIPTION
**Pull request by Aexousia**

### CODE REVIEW

**Comment by sharmaadityaHQ** [comment]
@Aexousia The cross entropy function is already available in the `costfunctions.py` and we've to just add it to the`network.py`. It particularly needs to be referenced in order to avoid overwriting the code and give a choice

**Comment by DantrazTrev** [comment]
@Aexousia  The cross-entropy function is already available as a class's static method in the `costfunctions.py` and we've to just add it to the`network.py`. It particularly needs to be referenced to avoid overwriting the code and have a choice. Also the cross-entropy function referenced there has it's derivative also. I know there is a bit ambiguity I'll resolve it by adding a simple CLI based choice.  Great job with the PR.

**Comment by Aexousia** [comment]
I have refered the cost function in the network file. Is this okay?

**Comment by DantrazTrev** [comment]
Hi @Aexousia There is still a need to create a UI for so I am not closing the issue. But good work

**Comment by aryancoolvats** [comment]
# hi i am ayush pratap singh and I pretend to be a beautiful girl from norway but in reality i'm just some dude.                 
poop           
i have a norwegian flag on my profile even though i am nowhere even related to it.        
poopy           
on my instagram page i come up with laughably terrible posts like this one                                  
lolswtfisthisshit

**Comment by aryancoolvats** [comment]
# hi i am ayush pratap singh and I pretend to be a beautiful girl from norway but in reality i'm just some dude.                 
poop           
i have a norwegian flag on my profile even though i am nowhere even related to it.        
poopy           
on my instagram page i come up with laughably terrible posts like this one                                  
lolswtfisthisshit

**Pull request merged**
